require("dotenv").config()
const express = require("express")
const categoryRouter = require("./routes/category")
const postsRouter = require("./routes/posts")
const usersRouter = require("./routes/users")
const cors = require("cors")
const app = express()
const { postInfoRouter } = require("./routes/postInfo")
const bodyParser = require("body-parser")
const foldersRouter = require("./routes/folders")
const stackRouter = require("./routes/stack")
const interactionsRouter = require("./routes/interactions")
const queryRouter = require("./routes/queryRouter")
const utilRouter = require("./routes/_")
const searchRouter = require("./routes/search")
app.use(cors())
app.use(bodyParser.json())

app.use("/_", utilRouter)
app.use("/categories", queryRouter)
app.use("/folders", queryRouter)
app.use("/search", queryRouter)
app.use("/folders", foldersRouter)
app.use("/posts", queryRouter)
app.use("/interactions", queryRouter)
app.use("/users", queryRouter)
app.use("/categories", categoryRouter)
app.use("/posts", postsRouter)
app.use("/search", searchRouter)
app.use("/users", usersRouter)
app.use("/stack", stackRouter)
app.use("/interactions", interactionsRouter)
postsRouter.use("/:id/", postInfoRouter)
foldersRouter.use("/:id/", postInfoRouter)
categoryRouter.use("/:id/", postInfoRouter)

app.listen(process.env.PORT, () => {
	console.log("Server is listening in http://localhost:" + process.env.PORT)
})
